openapi: 3.1.0
info:
  version: 1.0.0
  title: Enviame Stage Enviroment
  termsOfService: 'https://example.com/terms/'
  contact:
    email: support@enviame.io
    url: 'https://enviame.io/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://enviame.io/wp-content/uploads/2020/09/logo-enviame-dark.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Deliveries
    description: In this section are listed all the endpoints related with deliveries creation, label printing and manifest generation.
  - name: Company
    description: Operations about users.
  - name: Pick up
    description: This is a tag description.
servers:
  - url: 'https://stage.api.enviame.io/api/s2/v2/'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  '/users/{username}':
    $ref: 'paths/users_{username}.yaml'
  'marketplaces/{MarketplaceID}/companies/{SellerID}/deliveries'
    $ref: paths/mkt_to_seller.yaml
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
